{% set data = load_setup_py_data() %}

package:
  name: q2-feature-classifier
  version: {{ data.get('version') }}

source:
  path: ../..

build:
  script: python setup.py install

requirements:
  build:
    - python 3.5*
    - setuptools
    - scikit-learn
    - scikit-bio
    - biom-format >=2.1.5,<2.2.0
    - qiime2 2017.3.*
    - q2-types 2017.3.*
    - blast 2.6.0
    - vsearch 2.3.2

  run:
    - python 3.5*
    - setuptools
    - scikit-learn
    - scikit-bio
    - biom-format >=2.1.5,<2.2.0
    - qiime2 2017.3.*
    - q2-types 2017.3.*
    - blast 2.6.0
    - vsearch 2.3.2

test:
  imports:
    - q2_feature_classifier
    - qiime2.plugins.feature_classifier

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
